# This is a config for E2B sandbox template.
# You can use template ID (2yrhw0ev8i82rynrowgw) or template name (vibe-stack-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-stack-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-stack-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-stack-test2')

team_id = "69d9ec65-dba9-43bd-a807-b897700ea144"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-stack-test2"
template_id = "2yrhw0ev8i82rynrowgw"
